kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: ai-server-scaler
  namespace: tutti
spec:
  hosts:
    - ai-server.tutti.svc.cluster.local
  scaleTargetRef:
    name: ai-server
    kind: Deployment
    apiVersion: apps/v1
    service: ai-server
    port: 8000
  replicas:
    min: 0
    max: 3
